### ISSUE TITLE
Can't move to new pages in the book by right clicking the item icons in the book

### ISSUE THREAD

**Issue by ZophiaMarie** [JoeFoxe/Hexerei-0.2.1-1.18#3]
I'm not sure if it's just me so I figured I would report it. 

Minecraft Version: 1.19.1

Hexerie Version: 0.2.3

Forge: 42.0.9

I also have Ars Nouveau, Curios API, GeckoLib, JEI, and Patchouli though I dont think their relevant. Just listing for extra info in cause its needed,

Issue: I can no longer click on the Book of Shadows to flip to items in the book

https://user-images.githubusercontent.com/110948107/184269307-d08a4fa0-9081-4891-90bf-7db901c291b1.mp4

Hopefully this is helpful

**Comment by JoeFoxe** [comment]
fixed in 0.2.4 :)
