### ISSUE TITLE
Your Mod crashes with arsnouveau

### ISSUE THREAD

**Issue by ModernGamingWorld** [JoeFoxe/Hexerei-0.2.1-1.18#50]
[crash-2023-05-28_23.13.13-client.txt](https://github.com/JoeFoxe/Hexerei-1.19/files/11588382/crash-2023-05-28_23.13.13-client.txt)

**Comment by JoeFoxe** [comment]
damn okay I will talk to alex and look into this to see if there is a remedy for this

**Comment by ModernGamingWorld** [comment]
Okay, Best of Luck

**Comment by DiegoValdez1** [comment]
its only the newest version: 0.3.2 which did something with dynamic lights which crashes.

**Comment by Brcyden** [comment]
same issue

**Comment by JoeFoxe** [comment]
update to 0.3.2.1 to fix :)
