### ISSUE TITLE
Crash server on start

### ISSUE THREAD

**Issue by bigenergy** [JoeFoxe/Hexerei-0.2.1-1.18#52]
hexerei-0.3.2.1

https://gist.github.com/bigenergy/3d185fda87db9de8227a15bb56fcea87

**Comment by JoeFoxe** [comment]
could you try to reset your configs folders for hexerei?

**Comment by bigenergy** [comment]
> could you try to reset your configs folders for hexerei?

I deleted Hexerei-common.toml, It did not help
I wanted to add, the problem arose when updating from the version 0.3.0

**Comment by DelviousCrafts** [comment]
Also running into this issue. Have deleted all configs related to Hexerei on both server and client and let them regenerate. Still crashing on startup. Client loads with no issues

**Comment by JoeFoxe** [comment]
Okay I am looking into the reason why, I will hopefully have a fix tonight/tomorrow otherwise I will do a bandaid fix and remove the crashing bits or remove dynamic light functionality for now until its properly tested

**Comment by JoeFoxe** [comment]
Fixed in the latest version 0.3.2.2 - now it should load on servers :)
