### ISSUE TITLE
Latest mod still listed as 0.3.2

### ISSUE THREAD

**Issue by ColonelGerdauf** [JoeFoxe/Hexerei-0.2.1-1.18#68]
This is especially awkward where launchers check for mod updates, and repeatedly cite Hexerei as updateable no matter what is done on the player side

**Comment by ColonelGerdauf** [comment]
One elements that I have discovered, is that the metadata version on the file has not been touched since 0.3.2, which does not help the situation.

**Comment by JoeFoxe** [comment]
sorry fixing this, rushed this update because many people needed it and I have limited time to work on it, pushing the update now

**Comment by ColonelGerdauf** [comment]
Speaking of it, I wonder if it is viable to allow API access in the Licences tab
It would make it easier for people to download the mod thru the launchers
