### ISSUE TITLE
Why block auto-downloads through curseforge API

### ISSUE THREAD

**Issue by PostWarTacos** [JoeFoxe/Hexerei-0.2.1-1.18#72]
You're just trying to make this more difficult. Forcing me to script a solution that'll search for the most recent update, download it, and place it in the folder. thanks

**Comment by PostWarTacos** [comment]
🙄 🙄  massive ****head.

**Comment by JoeFoxe** [comment]
just dont use my mod then, I never said you had to, I dont give a single fuck that you have a headache honestly, entitled ass
