### ISSUE TITLE
Reloading resources crashes the game

### ISSUE THREAD

**Issue by ochotonida** [JoeFoxe/Hexerei-0.2.1-1.18#9]
Opening and closing the resource pack menu or pressing F3+t while in-game crashes the game.

Versions:
- Hexerei 0.2.4
- Forge 43.1.1

Crash log: https://paste.gg/p/anonymous/bc9d65db4df142b69366aa2f93a7990c

**Comment by JoeFoxe** [comment]
yea sorry about that, the next one fixes this bug, will be released within a week or two after I release it for my patron server
