### ISSUE TITLE
All mixed recipes that use lava cannot be crafted

### ISSUE THREAD

**Issue by Junnaturefox** [JoeFoxe/Hexerei-0.2.1-1.18#96]
Game version: 1.20.1
Mod version: 0.4.1

All mixes recipes using lava are required to be heated with a heat source, and the required heat source is shown as ‘Air’
This causes all mixed recipes that use lava to not be crafted
![QQ20240814-164225](https://github.com/user-attachments/assets/21441f97-f4ac-4e4c-b2ac-9ccbfaf33531)
![QQ20240814-165008](https://github.com/user-attachments/assets/e2f48273-eb25-4788-ad0c-04fbc0bc3c12)

Tested with only JEI and Hexerei mod installed and the issue still exists.

**Comment by RyanIsAinmDom** [comment]
Same issue here.

Edit:
I've been told by users on my server that putting fire under the cauldron fixes the issue.
